"use client";
import { useEffect, useState, type FormEvent } from "react";
import api from "@/lib/axios";
import { toast } from "sonner";
const fields = ["site_name", "site_tagline", "site_url", "default_meta_title", "default_meta_description", "default_meta_keywords", "contact_email", "contact_phone", "contact_address", "facebook", "twitter", "linkedin", "github", "youtube", "instagram", "google_search_console_id"] as const;
type Settings = Record<string, string | null>;
export default function Page() {
 const [settings, setSettings] = useState<Settings>(); useEffect(() => { api.get("/admin/settings").then(r => { const data = r.data.data; setSettings({ ...data, ...data.social, ...data.analytics }); }).catch(() => toast.error("Could not load settings")); }, []);
 async function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); try { await api.put("/admin/settings", Object.fromEntries(new FormData(e.currentTarget))); toast.success("Settings saved"); } catch { toast.error("Could not save settings"); } }
 async function upload(e: FormEvent<HTMLFormElement>) { e.preventDefault(); try { await api.post("/admin/settings/assets", new FormData(e.currentTarget), { headers: { "Content-Type": "multipart/form-data" } }); toast.success("Assets uploaded"); } catch { toast.error("Could not upload assets"); } }
 return <div><h1 className="text-3xl font-bold">Site settings</h1><p className="mt-2 text-muted-foreground">GA4 is configured in the frontend environment with NEXT_PUBLIC_GA_ID.</p>{settings ? <><form onSubmit={save} className="mt-6 grid max-w-3xl gap-4 rounded-xl border bg-background p-6 md:grid-cols-2">{fields.map(field => <label key={field} className="text-sm font-semibold">{field.replaceAll("_", " ")}<input name={field} type={field.includes("email") ? "email" : field.includes("url") || ["facebook", "twitter", "linkedin", "github", "youtube", "instagram"].includes(field) ? "url" : "text"} required={field === "site_name"} defaultValue={settings[field] || ""} className="mt-2 w-full rounded-lg border bg-background p-3" /></label>)}<button className="rounded-lg bg-[#165e46] px-5 py-3 text-white">Save settings</button></form><form onSubmit={upload} className="mt-6 max-w-3xl space-y-4 rounded-xl border bg-background p-6"><h2 className="text-xl font-bold">Brand assets</h2><label className="block">Logo<input type="file" name="logo" accept="image/*" className="block" /></label><label className="block">Favicon<input type="file" name="favicon" accept="image/*" className="block" /></label><button className="rounded-lg border px-5 py-2">Upload assets</button></form></> : <p className="mt-6">Loading…</p>}</div>;
}
