"use client";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import api from "@/lib/axios";
import { PageSizeSelect, type PageSize } from "@/components/admin/page-size";
type Row = { id: number; name: string; brand?: { name: string } | null; impressions_count: number; clicks_count: number; ctr: number };
type Group = { id: number; name: string; impressions_count: number; clicks_count: number };
type Placement = { placement: string; impressions: number; clicks: number };
type Daily = { date: string; kind: string; total: number };
type Data = { products: Row[]; brands: Group[]; networks: Group[]; placements: Placement[]; daily: Daily[]; totals: { impressions: number; clicks: number }; pagination: { current_page: number; last_page: number } };
export default function AnalyticsPage() {
  const [page, setPage] = useState(1); const [size, setSize] = useState<PageSize>(20); const [demo, setDemo] = useState(false);
  const { data, isLoading, error, refetch } = useQuery({ queryKey: ["affiliate-analytics", page, size, demo], queryFn: async () => (await api.get<{ data: Data }>("/admin/affiliate-analytics", { params: { page, per_page: size, demo: demo ? 1 : 0 } })).data.data });
  return <div><h1 className="text-3xl font-bold">Affiliate analytics</h1><p className="mt-2 text-muted-foreground">First-party database impressions and clicks by product, brand, network, placement and date. Google Analytics reports separately in GA4.</p><label className="mt-4 flex cursor-pointer items-center gap-2"><input type="checkbox" checked={demo} onChange={event => { setDemo(event.target.checked); setPage(1); }} /> Show demo seed data</label>{demo && <p role="status" className="mt-3 rounded-lg border border-amber-500 bg-amber-50 p-3 text-amber-950">Demo dataset only. These numbers are simulated and do not represent real visitor activity.</p>}
    {isLoading && <p className="mt-6">Loading analytics…</p>}{error && <p role="alert" className="mt-6 text-destructive">Could not load analytics. <button onClick={() => refetch()} className="cursor-pointer underline">Retry</button></p>}
    {data && <><div className="mt-6 grid gap-4 sm:grid-cols-3">{[["Impressions", data.totals.impressions], ["Affiliate clicks", data.totals.clicks], ["CTR", `${data.totals.impressions ? (100 * data.totals.clicks / data.totals.impressions).toFixed(1) : 0}%`]].map(([label, value]) => <div key={label} className="rounded-xl border bg-background p-5"><p className="text-sm">{label}</p><strong className="text-3xl">{value}</strong></div>)}</div>
      <div className="mt-8 grid gap-8 xl:grid-cols-2">{[["Brands", data.brands], ["Affiliate networks", data.networks]].map(([label, groups]) => <section key={label as string}><h2 className="text-xl font-bold">{label as string}</h2><div className="mt-3 overflow-x-auto rounded-xl border bg-background"><table className="w-full text-left text-sm"><thead><tr><th className="p-3">Name</th><th className="p-3">Impressions</th><th className="p-3">Clicks</th></tr></thead><tbody>{(groups as Group[]).map(group => <tr key={group.id} className="border-t"><td className="p-3">{group.name}</td><td className="p-3">{group.impressions_count}</td><td className="p-3">{group.clicks_count}</td></tr>)}</tbody></table></div></section>)}</div>
      <section className="mt-8"><h2 className="text-xl font-bold">Placements</h2><div className="mt-3 flex flex-wrap gap-3">{data.placements.map(item => <div key={item.placement} className="rounded-xl border bg-background p-4 text-sm"><strong>{item.placement.replaceAll("_", " ")}</strong><p>{item.impressions} impressions · {item.clicks} clicks</p></div>)}</div></section>
      <section className="mt-8"><h2 className="text-xl font-bold">Recent dates</h2><div className="mt-3 flex flex-wrap gap-3">{data.daily.map(item => <span key={`${item.date}-${item.kind}`} className="rounded-lg border bg-background px-4 py-2 text-sm">{item.date}: {item.total} {item.kind}s</span>)}</div></section>
      <section className="mt-8"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-bold">Products</h2><PageSizeSelect value={size} onChange={value => { setSize(value); setPage(1); }} /></div><div className="mt-3 overflow-x-auto rounded-xl border bg-background"><table className="w-full text-left text-sm"><thead><tr><th className="p-3">Product</th><th className="p-3">Brand</th><th className="p-3">Impressions</th><th className="p-3">Clicks</th><th className="p-3">CTR</th></tr></thead><tbody>{data.products.map(product => <tr key={product.id} className="border-t"><td className="p-3">{product.name}</td><td className="p-3">{product.brand?.name || "—"}</td><td className="p-3">{product.impressions_count}</td><td className="p-3">{product.clicks_count}</td><td className="p-3">{product.ctr}%</td></tr>)}</tbody></table></div><div className="mt-4 flex gap-4"><button className="cursor-pointer disabled:cursor-default" disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</button><span>{page} / {data.pagination.last_page}</span><button className="cursor-pointer disabled:cursor-default" disabled={page >= data.pagination.last_page} onClick={() => setPage(page + 1)}>Next</button></div></section></>}
  </div>;
}
