"use client";
import { useEffect, useState } from "react";
import api from "@/lib/axios";
import { toast } from "sonner";
import { PageSizeSelect, type PageSize } from "@/components/admin/page-size";
import type { PaginationMeta } from "@/types/api";
type Item = { id: number; name?: string; email?: string; subject?: string; message?: string; comment?: string; status?: string | boolean; post?: { title: string }; [key: string]: unknown };
type Kind = "comments" | "contact" | "newsletter";
const config: Record<Kind, { title: string; path: string; actions: { label: string; suffix: string; method: "patch" | "delete"; body?: object }[] }> = {
 comments: { title: "Comments", path: "comments", actions: [{ label: "Approve", suffix: "approve", method: "patch" }, { label: "Reject", suffix: "reject", method: "patch" }, { label: "Spam", suffix: "spam", method: "patch" }, { label: "Delete", suffix: "", method: "delete" }] },
 contact: { title: "Contact messages", path: "contact/messages", actions: [{ label: "Mark read", suffix: "read", method: "patch" }, { label: "Archive", suffix: "archive", method: "patch" }, { label: "Restore", suffix: "restore", method: "patch" }, { label: "Delete", suffix: "", method: "delete" }] },
 newsletter: { title: "Newsletter subscribers", path: "newsletter/subscribers", actions: [{ label: "Activate", suffix: "status", method: "patch", body: { status: true } }, { label: "Unsubscribe", suffix: "status", method: "patch", body: { status: false } }, { label: "Delete", suffix: "", method: "delete" }] },
};
export function Inbox({ kind }: { kind: Kind }) {
 const { title, path, actions } = config[kind]; const [items, setItems] = useState<Item[]>([]); const [meta, setMeta] = useState<PaginationMeta>(); const [page, setPage] = useState(1); const [size, setSize] = useState<PageSize>(20); const [status, setStatus] = useState(""); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [revision, setRevision] = useState(0);
 useEffect(() => { let active = true; api.get(`/admin/${path}`, { params: { page, per_page: size, status: status || undefined, search: search || undefined } }).then(r => { if (active) { setItems(r.data.data || []); setMeta(r.data.meta); } }).catch(() => toast.error(`Could not load ${title.toLowerCase()}`)).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [page, size, status, search, path, title, revision]);
 async function act(item: Item, action: typeof actions[number]) { if (action.method === "delete" && !window.confirm("Delete this record?")) return; const url = `/admin/${path}/${item.id}${action.suffix ? `/${action.suffix}` : ""}`; try { if (action.method === "delete") await api.delete(url); else await api.patch(url, action.body || {}); toast.success("Updated"); setRevision(v => v + 1); } catch { toast.error("Could not update this record"); } }
 return <div><h1 className="text-3xl font-bold">{title}</h1><div className="mt-6 flex flex-wrap gap-3"><input type="search" value={search} onChange={e => { setPage(1); setSearch(e.target.value); }} placeholder="Search" className="rounded-lg border p-3" /><select value={status} onChange={e => { setPage(1); setStatus(e.target.value); }} className="rounded-lg border p-3"><option value="">All statuses</option>{(kind === "comments" ? ["pending", "approved", "rejected", "spam"] : kind === "contact" ? ["new", "read", "archived"] : ["true", "false"]).map(s => <option key={s} value={s}>{s}</option>)}</select><PageSizeSelect value={size} onChange={value => { setSize(value); setPage(1); }} /></div>
 <div className="mt-6 space-y-4">{items.map(item => <article key={item.id} className="rounded-xl border bg-background p-5"><div className="flex flex-wrap justify-between gap-3"><strong>{item.subject || item.name || item.email}</strong><span className="text-sm text-slate-500">{String(item.status)}</span></div>{item.post && <p className="mt-2 text-sm">On: {item.post.title}</p>}<p className="mt-3 whitespace-pre-wrap text-sm">{item.message || item.comment || item.email}</p><div className="mt-5 flex flex-wrap gap-2">{actions.map(action => <button key={action.label} onClick={() => act(item, action)} className="rounded-lg border px-3 py-2 text-sm hover:bg-muted">{action.label}</button>)}</div></article>)}{loading && <p>Loading…</p>}{!loading && !items.length && <p>No records found.</p>}</div>{meta && meta.last_page > 1 && <div className="mt-5 flex gap-3"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="rounded border px-3 py-2">Previous</button><span>{page} / {meta.last_page}</span><button disabled={page >= meta.last_page} onClick={() => setPage(page + 1)} className="rounded border px-3 py-2">Next</button></div>}</div>;
}
