"use client";
import { useEffect, useState, type FormEvent } from "react";
import Image from "next/image";
import { imageUrl } from "@/lib/image";
import api from "@/lib/axios";
import { toast } from "sonner";
import { PageSizeSelect, type PageSize } from "@/components/admin/page-size";
type Banner = { id: number; heading: string; description: string | null; background_image: string | null; cta_text: string | null; cta_url: string | null; enabled: boolean; sort_order: number };
export default function Page() {
 const [items,setItems] = useState<Banner[]>([]); const [editing,setEditing] = useState<Banner | "new" | null>(null); const [page,setPage] = useState(1); const [size,setSize] = useState<PageSize>(20); const [last,setLast] = useState(1); const [revision,setRevision] = useState(0);
 useEffect(() => { api.get("/admin/hero-banners",{params:{page,per_page:size}}).then(r=>{setItems(r.data.data);setLast(r.data.meta.last_page);}).catch(()=>toast.error("Could not load hero banners")); },[page,size,revision]);
 async function save(e:FormEvent<HTMLFormElement>) {e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const payload={...data,enabled:data.enabled==="on",sort_order:Number(data.sort_order)};try{if(editing && editing!=="new") await api.put(`/admin/hero-banners/${editing.id}`,payload); else await api.post("/admin/hero-banners",payload);setEditing(null);setRevision(x=>x+1);toast.success("Banner saved");}catch{toast.error("Could not save banner; check required fields");}}
 async function remove(id:number){if(!window.confirm("Delete this banner?"))return;try{await api.delete(`/admin/hero-banners/${id}`);setRevision(x=>x+1);toast.success("Banner deleted");}catch{toast.error("Could not delete banner");}}
 return <div><div className="flex items-center justify-between gap-3"><h1 className="text-3xl font-bold">Hero banners</h1><button onClick={()=>setEditing("new")} className="rounded-lg bg-primary px-4 py-2 text-primary-foreground">Add banner</button></div><p className="mt-3 text-sm text-muted-foreground">Displayed after the affiliate carousel. Use an image path from the media library.</p>
 {editing && <form key={editing==="new"?"new":editing.id} onSubmit={save} className="mt-6 grid gap-4 rounded-xl border bg-background p-5 sm:grid-cols-2">{(["heading","description","background_image","cta_text","cta_url","sort_order"] as const).map(field=><label key={field} className="text-sm font-semibold">{field.replaceAll("_"," ")}<input required={field==="heading"||field==="sort_order"} type={field==="sort_order"?"number":"text"} name={field} defaultValue={editing==="new"?(field==="sort_order"?"0":""):editing[field]??""} className="mt-1 block w-full rounded-lg border bg-background p-3" /></label>)}<label className="flex items-center gap-2">Enabled <input type="checkbox" name="enabled" defaultChecked={editing==="new"||editing.enabled} /></label><div className="flex gap-3"><button className="rounded-lg bg-primary px-4 py-2 text-primary-foreground">Save</button><button type="button" onClick={()=>setEditing(null)} className="rounded-lg border px-4 py-2">Cancel</button></div></form>}
 <div className="mt-6 flex justify-end"><PageSizeSelect value={size} onChange={value=>{setSize(value);setPage(1);}} /></div><div className="mt-4 grid gap-4">{items.map(banner=><article key={banner.id} className="flex flex-wrap items-center gap-4 rounded-xl border bg-background p-4">{banner.background_image&&<Image unoptimized src={imageUrl(banner.background_image)} alt="" width={144} height={84} className="h-20 w-36 rounded-lg object-cover" />}<div className="flex-1"><h2 className="font-bold">{banner.heading}</h2><p className="text-sm text-muted-foreground">{banner.enabled?"Enabled":"Disabled"} · Order {banner.sort_order}</p></div><button onClick={()=>setEditing(banner)} className="text-primary">Edit</button><button onClick={()=>remove(banner.id)} className="text-destructive">Delete</button></article>)}</div><div className="mt-5 flex gap-3"><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span>{page} / {last}</span><button disabled={page>=last} onClick={()=>setPage(page+1)}>Next</button></div></div>;
}
