"use client";
import { useEffect, useState, type FormEvent } from "react";
import api from "@/lib/axios";
import { toast } from "sonner";
type Profile = { name: string; username?: string; email: string; phone?: string; avatar?: string };
export default function Page() {
 const [profile, setProfile] = useState<Profile>(); useEffect(() => { api.get("/admin/profile").then(r => setProfile(r.data.data)).catch(() => toast.error("Could not load profile")); }, []);
 async function update(e: FormEvent<HTMLFormElement>) { e.preventDefault(); try { await api.put("/admin/profile", Object.fromEntries(new FormData(e.currentTarget))); toast.success("Profile saved"); } catch { toast.error("Could not save profile"); } }
 async function password(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = e.currentTarget; try { await api.put("/admin/profile/password", Object.fromEntries(new FormData(form))); toast.success("Password changed"); form.reset(); } catch { toast.error("Could not change password"); } }
 async function avatar(e: FormEvent<HTMLFormElement>) { e.preventDefault(); try { await api.post("/admin/profile/avatar", new FormData(e.currentTarget), { headers: { "Content-Type": "multipart/form-data" } }); toast.success("Avatar updated"); } catch { toast.error("Could not update avatar"); } }
 return <div className="max-w-xl"><h1 className="text-3xl font-bold">Profile</h1>{profile ? <><form onSubmit={update} className="mt-6 space-y-4 rounded-xl border bg-white p-6">{(["name", "username", "phone"] as const).map(field => <label key={field} className="block text-sm font-semibold">{field}<input name={field} defaultValue={profile[field] || ""} required={field === "name"} className="mt-2 w-full rounded-lg border p-3" /></label>)}<p className="text-sm">Email: {profile.email}</p><button className="rounded-lg bg-[#165e46] px-5 py-2 text-white">Save profile</button></form><form onSubmit={avatar} className="mt-6 rounded-xl border bg-white p-6"><h2 className="mb-4 text-xl font-bold">Avatar</h2><input name="avatar" type="file" accept="image/*" required /><button className="mt-4 block rounded-lg border px-5 py-2">Upload avatar</button></form><form onSubmit={password} className="mt-6 space-y-4 rounded-xl border bg-white p-6"><h2 className="text-xl font-bold">Change password</h2>{["current_password", "password", "password_confirmation"].map(field => <label key={field} className="block text-sm">{field.replaceAll("_", " ")}<input name={field} type="password" required className="mt-2 w-full rounded-lg border p-3" /></label>)}<button className="rounded-lg border px-5 py-2">Change password</button></form></> : <p className="mt-6">Loading…</p>}</div>;
}
